import type { Course } from "@nursepath/shared";

/**
 * NCM 103 — Fundamentals of Nursing Practice (FLAGSHIP).
 *
 * This is the example course from the spec and the deepest-authored course in
 * the catalog. Content is research-backed:
 *  - Vital signs normal ranges: Cleveland Clinic / Johns Hopkins / MedlinePlus
 *  - Infection control: CDC Standard Precautions + WHO "My Five Moments"
 *  - Medication safety: StatPearls/NIH — 10 Rights of Medication Administration
 */
export const ncm103: Course = {
  code: "NCM 103",
  title: "Fundamentals of Nursing Practice",
  category: "NCM",
  tagline: "The bedrock of nursing: patient care, vital signs, infection control, and medications.",
  icon: "👩‍⚕️",
  hours: 60,
  outcomes: [
    "Apply the nursing process (ADPIE) to real patient scenarios",
    "Measure and interpret all five vital signs accurately",
    "Perform CDC Standard Precautions and WHO Five Moments for hand hygiene",
    "Administer medications safely using the 10 Rights",
    "Document care clearly and communicate clinically",
    "Respond to common emergencies with first-responder actions",
  ],
  units: [
    {
      id: "ncm103-u1",
      title: "Introduction to Nursing",
      summary: "History, the nursing process, and the nurse's professional role.",
      icon: "🩺",
      hours: 10,
      pathways: [
        {
          id: "ncm103-u1-p1",
          title: "The Nursing Process (ADPIE)",
          summary: "Assess, Diagnose, Plan, Implement, Evaluate — your clinical compass.",
          icon: "🧭",
          steps: [
            {
              id: "ncm103-u1-p1-s-video",
              kind: "video",
              title: "Introduction to the Nursing Process",
              summary: "A 6-minute orientation to ADPIE.",
              minutes: 6,
              url: "https://www.youtube.com/watch?v=gUWJ-6nL5-8",
              transcript:
                "The nursing process is a systematic, five-step method nurses use to deliver care: Assessment, Diagnosis, Planning, Implementation, and Evaluation. It is deliberate, cyclic, and patient-centred.",
            },
            {
              id: "ncm103-u1-p1-s-reading",
              kind: "reading",
              title: "ADPIE: The Five Steps",
              summary: "What each phase looks like at the bedside.",
              minutes: 8,
              source: "OpenStax, Fundamentals of Nursing",
              body: [
                "**Assessment** — collect subjective (what the patient says) and objective (what you measure) data.",
                "",
                "**Diagnosis** — formulate a nursing diagnosis (NANDA-I), e.g. *Risk for Infection*.",
                "",
                "**Planning** — set SMART goals and pick evidence-based interventions.",
                "",
                "**Implementation** — carry out the interventions (medications, teaching, procedures).",
                "",
                "**Evaluation** — measure the patient's response against the goals and revise the plan.",
              ].join("\n"),
              takeaways: [
                "ADPIE is cyclic — evaluation loops back to assessment.",
                "Subjective data = patient's words; objective data = measurable signs.",
                "Nursing diagnoses differ from medical diagnoses.",
              ],
            },
            {
              id: "ncm103-u1-p1-s-practice",
              kind: "practice",
              title: "Write a Nursing Care Plan",
              summary: "Draft an ADPIE care plan for a post-op patient.",
              minutes: 15,
              skills: ["care-planning"],
              checklist: [
                "Assess: record 2 objective + 2 subjective findings",
                "Write one NANDA-I nursing diagnosis",
                "Set one SMART goal with a timeframe",
                "List 3 interventions with rationales",
                "State how you would evaluate the goal",
              ],
              equipment: ["Care plan template", "Patient scenario sheet"],
            },
            {
              id: "ncm103-u1-p1-s-sim",
              kind: "simulation",
              simKind: "decision",
              title: "Patient Scenario: The New Admission",
              summary: "A 58-year-old is admitted with cellulitis. Apply the nursing process.",
              minutes: 10,
              skills: ["care-planning"],
              entry: "start",
              nodes: {
                start: {
                  id: "start",
                  scenario:
                    "Mr. Reyes, 58, is admitted with right-leg cellulitis. Vitals: T 38.4°C, HR 96, RR 20, BP 128/78, SpO₂ 97%. What is your FIRST nursing action?",
                  patient: {
                    name: "Mr. Reyes",
                    age: 58,
                    sex: "M",
                    vitals: {
                      Temp: "38.4°C (febrile)",
                      HR: "96 bpm",
                      RR: "20/min",
                      BP: "128/78 mmHg",
                      "SpO₂": "97%",
                    },
                    context: "Right-leg cellulitis, newly admitted.",
                  },
                  choices: [
                    {
                      id: "c1",
                      label: "Complete a head-to-toe assessment",
                      next: "assess",
                      feedback: "Correct — assessment always comes first to gather baseline data.",
                    },
                    {
                      id: "c2",
                      label: "Give acetaminophen for the fever immediately",
                      next: "rush",
                      feedback:
                        "Premature — you haven't assessed yet. Interventions flow from assessment.",
                    },
                    {
                      id: "c3",
                      label: "Page the physician for antibiotics",
                      next: "rush",
                      feedback: "The physician will be involved, but begin with your own assessment.",
                    },
                  ],
                },
                assess: {
                  id: "assess",
                  scenario:
                    "Good. Assessment reveals a warm, red, swollen right leg with intact skin. Pain 6/10. Which nursing diagnosis is most appropriate?",
                  choices: [
                    {
                      id: "a1",
                      label: "Impaired Skin Integrity related to infection",
                      next: "dx",
                      feedback: "Appropriate — it captures the tissue problem at the source.",
                    },
                    {
                      id: "a2",
                      label: "Acute Pain related to leg swelling",
                      next: "dx",
                      feedback: "Also valid, but secondary to the infection. Either is defensible here.",
                    },
                  ],
                },
                dx: {
                  id: "dx",
                  scenario:
                    "Now set a goal. Which is the best SMART goal for Impaired Skin Integrity?",
                  choices: [
                    {
                      id: "d1",
                      label:
                        "Patient's right leg redness and swelling will decrease within 72 hours of antibiotics and elevation.",
                      next: "win",
                      feedback: "SMART: specific, measurable, time-bound. Excellent.",
                    },
                    {
                      id: "d2",
                      label: "Patient will feel better soon.",
                      next: "vague",
                      feedback: "Not measurable or time-bound — refine it.",
                    },
                  ],
                },
                win: {
                  id: "win",
                  scenario: "Excellent work. You've completed a full ADPIE cycle.",
                  success: true,
                  debrief:
                    "You moved correctly: Assess → Diagnose → Plan. In practice you'd Implement (elevate leg, administer antibiotics, teach) and Evaluate in 72h.",
                },
                vague: {
                  id: "vague",
                  scenario:
                    "Revisit: tie the goal to a measurable sign and a timeframe, then continue.",
                  debrief:
                    "Vague goals can't be evaluated. Always include a measurable indicator and a deadline.",
                  choices: [{ id: "v1", label: "Rewrite the goal", next: "dx" }],
                },
                rush: {
                  id: "rush",
                  scenario:
                    "Remember: assessment precedes intervention. Restart from the patient.",
                  debrief:
                    "Skipping assessment risks missing critical data. Return to the bedside first.",
                  choices: [{ id: "r1", label: "Go back and assess", next: "start" }],
                },
              },
            },
            {
              id: "ncm103-u1-p1-s-quiz",
              kind: "quiz",
              title: "Quiz: The Nursing Process",
              summary: "5 questions on ADPIE.",
              minutes: 8,
              passThreshold: 0.7,
              questions: [
                {
                  id: "q1",
                  prompt: "Which phase of the nursing process comes FIRST?",
                  options: ["Diagnosis", "Assessment", "Planning", "Evaluation"],
                  correctIndex: 1,
                  explanation: "Assessment gathers the baseline data that drives every other phase.",
                },
                {
                  id: "q2",
                  prompt: "A patient saying 'I feel nauseated' is an example of:",
                  options: [
                    "Objective data",
                    "Subjective data",
                    "A nursing diagnosis",
                    "An evaluation",
                  ],
                  correctIndex: 1,
                  explanation: "Subjective data is what the patient reports; objective data is measured.",
                },
                {
                  id: "q3",
                  prompt: "Which is the best example of a SMART goal?",
                  options: [
                    "Patient will improve.",
                    "Patient will ambulate 50 m with a walker by day 3 post-op.",
                    "Patient will walk when ready.",
                    "Patient will feel stronger soon.",
                  ],
                  correctIndex: 1,
                  explanation: "It is Specific, Measurable, Achievable, Relevant, and Time-bound.",
                },
                {
                  id: "q4",
                  prompt: "Evaluation mainly involves:",
                  options: [
                    "Collecting new admitting data",
                    "Comparing patient response to the goals set",
                    "Writing new diagnoses",
                    "Ordering labs",
                  ],
                  correctIndex: 1,
                  explanation: "Evaluation measures the patient's progress against the planned goals.",
                },
                {
                  id: "q5",
                  prompt: "The nursing process is best described as:",
                  options: ["Linear", "Cyclic and dynamic", "A one-time event", "Physician-led"],
                  correctIndex: 1,
                  explanation: "It is cyclic — evaluation loops back to reassessment.",
                },
              ],
            },
          ],
        },
      ],
    },

    {
      id: "ncm103-u2",
      title: "Vital Signs & Assessment",
      summary: "Measure and interpret temperature, pulse, respiration, BP, and SpO₂.",
      icon: "💓",
      hours: 12,
      pathways: [
        {
          id: "ncm103-u2-p1",
          title: "Measuring Vital Signs",
          summary: "Normal ranges, measurement techniques, and abnormal findings.",
          icon: "💓",
          steps: [
            {
              id: "ncm103-u2-p1-s-video",
              kind: "video",
              title: "Introduction to Vital Signs",
              summary: "The five vital signs and why they matter.",
              minutes: 7,
              url: "https://www.youtube.com/watch?v=gUWJ-6nL5-8",
              transcript:
                "The five vital signs are body temperature, pulse (heart rate), respiration rate, blood pressure, and oxygen saturation. They reflect the body's most basic physiological functions and are the fastest window into a patient's status.",
            },
            {
              id: "ncm103-u2-p1-s-reading",
              kind: "reading",
              title: "Blood Pressure Basics & Normal Ranges",
              summary: "Adult normal ranges and the hypertension categories.",
              minutes: 10,
              source: "Cleveland Clinic; Johns Hopkins Medicine; MedlinePlus (NIH)",
              skills: ["vital-signs"],
              body: [
                "## Normal adult vital signs",
                "",
                "| Sign | Normal adult range |",
                "|---|---|",
                "| **Temperature** | 36.5-37.3 °C (97.8-99.1 °F) |",
                "| **Pulse** | 60-100 bpm |",
                "| **Respiration** | 12-20 breaths/min |",
                "| **Blood pressure** | 90/60 to 120/80 mmHg |",
                "| **SpO2** | 96-100% |",
                "",
                "## Blood pressure categories",
                "",
                "- **Normal:** < 120 / < 80",
                "- **Elevated:** 120–129 / < 80",
                "- **Stage 1 HTN:** 130–139 / 80–89",
                "- **Stage 2 HTN:** ≥ 140 / ≥ 90",
                "- **Hypertensive crisis:** > 180 / > 120 — treat immediately",
                "",
                "> Ranges can vary slightly between sources and institutions; always follow your facility's policy.",
              ].join("\n"),
              takeaways: [
                "Adult pulse is 60–100 bpm; below 60 is bradycardia, above 100 is tachycardia.",
                "RR below 12 is bradypnea, above 20 is tachypnea.",
                "BP ≥ 130/80 meets the threshold for hypertension (Stage 1).",
                "SpO₂ < 92% is concerning and warrants prompt evaluation.",
              ],
            },
            {
              id: "ncm103-u2-p1-s-practice",
              kind: "practice",
              title: "Use the BP Apparatus",
              summary: "Step-by-step manual blood pressure measurement.",
              minutes: 15,
              skills: ["vital-signs", "bp-measurement"],
              checklist: [
                "Have the patient rest 5 minutes, feet flat, arm supported at heart level",
                "Select the correct cuff size (bladder ≥ 80% of arm circumference)",
                "Palpate the radial pulse and inflate 30 mmHg above its disappearance",
                "Deflate at 2–3 mmHg per second and note systolic then diastolic Korotkoff sounds",
                "Record both values, the arm used, and patient position",
              ],
              equipment: ["Sphygmomanometer", "Stethoscope", "Correctly sized cuff"],
            },
            {
              id: "ncm103-u2-p1-s-sim",
              kind: "simulation",
              simKind: "decision",
              title: "Patient Scenario: High Blood Pressure",
              summary: "A walk-in patient registers 168/98. What do you do?",
              minutes: 8,
              skills: ["vital-signs", "bp-measurement"],
              entry: "start",
              nodes: {
                start: {
                  id: "start",
                  scenario:
                    "Ms. Cruz, 64, walks in for a routine check. Her BP reads 168/98 mmHg. She is asymptomatic and feels well. What is your first action?",
                  patient: {
                    name: "Ms. Cruz",
                    age: 64,
                    sex: "F",
                    vitals: { BP: "168/98 mmHg", HR: "82 bpm", Symptoms: "None reported" },
                    context: "Routine check; no headache, no chest pain, no vision changes.",
                  },
                  choices: [
                    {
                      id: "c1",
                      label: "Recheck after she rests 5 minutes in a quiet room",
                      next: "recheck",
                      feedback:
                        "Best first step — confirm an elevated reading before acting, removing situational causes.",
                    },
                    {
                      id: "c2",
                      label: "Diagnose hypertension and start meds yourself",
                      next: "overreach",
                      feedback: "Nurses don't diagnose/prescribe alone — and you haven't confirmed the reading.",
                    },
                    {
                      id: "c3",
                      label: "Ignore it since she feels fine",
                      next: "miss",
                      feedback: "Dangerous — asymptomatic severe elevation still needs follow-up.",
                    },
                  ],
                },
                recheck: {
                  id: "recheck",
                  scenario:
                    "After 5 minutes rest, repeat BP = 166/96 mmHg. No red-flag symptoms (no chest pain, no neuro deficits). What now?",
                  choices: [
                    {
                      id: "r1",
                      label:
                        "Document, inform the patient, and arrange prompt medical follow-up today",
                      next: "win",
                      feedback:
                        "Confirmed Stage 2 reading without crisis symptoms → urgent outpatient follow-up, not necessarily the ER.",
                    },
                    {
                      id: "r2",
                      label: "Send her to the ER as an emergency",
                      next: "overtriage",
                      feedback:
                        "No end-organ symptoms, so this isn't a hypertensive crisis. Arrange prompt follow-up instead.",
                    },
                  ],
                },
                win: {
                  id: "win",
                  scenario:
                    "Well managed. Ms. Cruz is booked for same-day follow-up and taught home BP monitoring.",
                  success: true,
                  debrief:
                    "For asymptomatic BP ≥ 160/100: confirm, document, educate, and arrange prompt (often same-day) medical follow-up. Watch for crisis red flags: chest pain, severe headache, vision change, focal neuro signs, or BP > 180/120.",
                },
                overtriage: {
                  id: "overtriage",
                  scenario: "Reconsider the triage decision based on her symptom-free status.",
                  debrief:
                    "Hypertensive *crisis* requires end-organ symptoms or BP > 180/120. Without those, prompt outpatient follow-up is appropriate.",
                  choices: [{ id: "o1", label: "Reassess the plan", next: "recheck" }],
                },
                overreach: {
                  id: "overreach",
                  scenario: "Step back to your scope of practice.",
                  debrief:
                    "Confirm the reading, document, and refer — diagnosis/prescribing are collaborative.",
                  choices: [{ id: "or1", label: "Start over correctly", next: "start" }],
                },
                miss: {
                  id: "miss",
                  scenario: "Elevated readings always need follow-up, symptomatic or not.",
                  debrief:
                    "Hypertension is often silent. Missing it risks stroke, MI, and kidney damage down the line.",
                  choices: [{ id: "m1", label: "Take it seriously", next: "start" }],
                },
              },
            },
            {
              id: "ncm103-u2-p1-s-quiz",
              kind: "quiz",
              title: "Quiz: Vital Signs",
              summary: "6 questions on ranges and interpretation.",
              minutes: 10,
              passThreshold: 0.7,
              questions: [
                {
                  id: "q1",
                  prompt: "Normal adult resting heart rate is:",
                  options: ["30–50 bpm", "60–100 bpm", "100–120 bpm", "120–160 bpm"],
                  correctIndex: 1,
                  explanation: "60–100 bpm is the standard adult range.",
                },
                {
                  id: "q2",
                  prompt: "A respiratory rate of 26 breaths/min in an adult is:",
                  options: ["Normal", "Bradypnea", "Tachypnea", "Apnea"],
                  correctIndex: 2,
                  explanation: "Adult RR > 20 is tachypnea.",
                },
                {
                  id: "q3",
                  prompt: "Which BP reading meets Stage 2 hypertension?",
                  options: ["118/76", "128/82", "135/88", "146/92"],
                  correctIndex: 3,
                  explanation: "≥ 140 systolic or ≥ 90 diastolic is Stage 2.",
                },
                {
                  id: "q4",
                  prompt: "Before measuring BP, the patient should:",
                  options: [
                    "Drink coffee to relax",
                    "Rest quietly for ~5 minutes with feet flat",
                    "Stand with arms crossed",
                    "Talk on their phone",
                  ],
                  correctIndex: 1,
                  explanation: "5 minutes of rest in a supported position gives an accurate reading.",
                },
                {
                  id: "q5",
                  prompt: "An SpO₂ of 88% should prompt you to:",
                  options: [
                    "Document it as normal",
                    "Evaluate and notify the team promptly",
                    "Wait an hour and recheck",
                    "Tell the patient it's fine",
                  ],
                  correctIndex: 1,
                  explanation: "SpO₂ < 92% is concerning; < 90% is hypoxemia needing prompt action.",
                },
                {
                  id: "q6",
                  prompt: "Normal adult body temperature (oral) is approximately:",
                  options: ["33–35 °C", "36.5–37.3 °C", "38–39 °C", "40–41 °C"],
                  correctIndex: 1,
                  explanation: "36.5–37.3 °C (97.8–99.1 °F) is the normal oral range.",
                },
              ],
            },
          ],
        },
        {
          id: "ncm103-u2-p2",
          title: "Patient Assessment",
          summary: "Head-to-toe assessment and the focused exam.",
          icon: "🩺",
          steps: [
            {
              id: "ncm103-u2-p2-s-video",
              kind: "video",
              title: "Head-to-Toe Assessment Overview",
              summary: "A systematic 9-minute walkthrough.",
              minutes: 9,
              url: "https://www.youtube.com/watch?v=0uKfgNC8HKQ",
              transcript:
                "A head-to-toe assessment moves cephalocaudally (head to toe) and uses four techniques in order: inspection, palpation, percussion, and auscultation — except for the abdomen, which is inspect, auscultate, percuss, palpate so as not to alter bowel sounds.",
            },
            {
              id: "ncm103-u2-p2-s-reading",
              kind: "reading",
              title: "The Four Examination Techniques",
              summary: "Inspection, Palpation, Percussion, Auscultation.",
              minutes: 8,
              source: "OpenStax, Fundamentals of Nursing",
              skills: ["health-assessment"],
              body: [
                "1. **Inspection** — focused, deliberate visual observation (symmetry, colour, movement).",
                "2. **Palpation** — using touch (use the pads of the fingers; start light then deep).",
                "3. **Percussion** — tapping to assess underlying density (resonant, dull, hyperresonant).",
                "4. **Auscultation** — listening with a stethoscope (bowel, heart, lung sounds).",
                "",
                "> **Abdomen exception:** auscultate *before* palpation/percussion so you don't stimulate or alter bowel sounds.",
              ].join("\n"),
              takeaways: [
                "Order: Inspection → Palpation → Percussion → Auscultation.",
                "Abdomen: Inspection → Auscultation → Percussion → Palpation.",
                "Warm your hands and stethoscope before patient contact.",
              ],
            },
            {
              id: "ncm103-u2-p2-s-practice",
              kind: "practice",
              title: "Perform a Head-to-Toe Assessment",
              summary: "Check off each region in order.",
              minutes: 20,
              skills: ["health-assessment"],
              checklist: [
                "Introduce yourself, confirm identity, explain the exam, ensure privacy",
                "Neuro: mental status, pupils, grip strength",
                "HEENT: scalp, eyes, ears, nose, throat, neck mobility",
                "Chest: auscultate anterior and posterior lung fields",
                "Cardiovascular: apical pulse for one full minute",
                "Abdomen: inspect → auscultate → percuss → palpate",
                "Extremities: pulses, skin, range of motion, oedema",
                "Document findings and report abnormals",
              ],
              equipment: ["Stethoscope", "Penlight", "Reflex hammer", "Gloves"],
            },
            {
              id: "ncm103-u2-p2-s-quiz",
              kind: "quiz",
              title: "Quiz: Physical Assessment",
              summary: "4 questions on technique and order.",
              minutes: 6,
              passThreshold: 0.7,
              questions: [
                {
                  id: "q1",
                  prompt: "Correct order of abdominal assessment:",
                  options: [
                    "Inspect → Palpate → Percuss → Auscultate",
                    "Inspect → Auscultate → Percuss → Palpate",
                    "Auscultate → Inspect → Palpate → Percuss",
                    "Percuss → Auscultate → Inspect → Palpate",
                  ],
                  correctIndex: 1,
                  explanation:
                    "Auscultate before palpation/percussion to avoid altering bowel sounds.",
                },
                {
                  id: "q2",
                  prompt: "Which technique uses a stethoscope?",
                  options: ["Inspection", "Palpation", "Percussion", "Auscultation"],
                  correctIndex: 3,
                  explanation: "Auscultation = listening with the stethoscope.",
                },
                {
                  id: "q3",
                  prompt: "A dull percussion note over the lungs may suggest:",
                  options: ["Normal air", "Fluid or solid mass", "Excess air", "Nothing significant"],
                  correctIndex: 1,
                  explanation: "Dullness suggests fluid or solid tissue replacing air (e.g. effusion).",
                },
                {
                  id: "q4",
                  prompt: "Before palpation you should:",
                  options: [
                    "Warm your hands",
                    "Skip patient consent",
                    "Use cold fingers for sensitivity",
                    "Palpate surgical sites first",
                  ],
                  correctIndex: 0,
                  explanation: "Warm hands and short nails respect patient comfort and safety.",
                },
              ],
            },
          ],
        },
      ],
    },

    {
      id: "ncm103-u3",
      title: "Infection Control",
      summary: "CDC Standard Precautions, WHO hand hygiene, and transmission-based precautions.",
      icon: "🦠",
      hours: 10,
      pathways: [
        {
          id: "ncm103-u3-p1",
          title: "Standard Precautions & Hand Hygiene",
          summary: "The core practices that protect every patient, every time.",
          icon: "🧼",
          steps: [
            {
              id: "ncm103-u3-p1-s-video",
              kind: "video",
              title: "Standard Precautions in Practice",
              summary: "CDC core infection-prevention practices.",
              minutes: 8,
              transcript:
                "Standard Precautions apply to ALL patients because we can't always know who is infectious. The core: hand hygiene, personal protective equipment (PPE), safe injection practices, respiratory hygiene, and safe handling of equipment and surfaces.",
            },
            {
              id: "ncm103-u3-p1-s-reading",
              kind: "reading",
              title: "WHO My Five Moments for Hand Hygiene",
              summary: "When, exactly, to perform hand hygiene.",
              minutes: 7,
              source: "CDC Core Infection Prevention Practices; WHO 'My Five Moments'",
              skills: ["infection-control"],
              body: [
                "WHO's **My Five Moments for Hand Hygiene** pinpoints exactly when to clean your hands:",
                "",
                "1. **Before touching a patient**",
                "2. **Before a clean/aseptic procedure**",
                "3. **After body fluid exposure risk**",
                "4. **After touching a patient**",
                "5. **After touching patient surroundings**",
                "",
                "**Alcohol-based hand rub** is the routine choice for visibly clean hands.",
                "",
                "**Soap and water** is required when hands are visibly soiled, before eating, after using the restroom, and during care of patients with confirmed or suspected *C. difficile* or spore-forming organisms (alcohol doesn't kill spores).",
              ].join("\n"),
              takeaways: [
                "5 Moments: before patient, before aseptic task, after fluid risk, after patient, after surroundings.",
                "Alcohol rub for routine decontamination of visibly clean hands.",
                "Soap & water for visible soil, eating, restroom, and C. difficile.",
              ],
            },
            {
              id: "ncm103-u3-p1-s-practice",
              kind: "practice",
              title: "Handwashing Technique",
              summary: "Follow the WHO technique step by step.",
              minutes: 5,
              skills: ["infection-control"],
              checklist: [
                "Wet hands and apply soap",
                "Palm to palm with fingers interlaced",
                "Backs of hands and between fingers",
                "Rotational rubbing of thumbs and fingertips",
                "Rinse and dry thoroughly with a single-use towel",
                "Total duration 40–60 seconds",
              ],
              equipment: ["Soap", "Running water", "Single-use towel"],
            },
            {
              id: "ncm103-u3-p1-s-sim",
              kind: "simulation",
              simKind: "sequence",
              title: "Donning PPE in the Correct Order",
              summary: "Drag the steps into the right order for putting PPE on.",
              minutes: 5,
              skills: ["infection-control"],
              instruction: "Arrange the PPE donning steps in the correct order (top = first).",
              items: [
                "Perform hand hygiene",
                "Put on the gown, tie at neck and waist",
                "Put on the mask or respirator",
                "Put on goggles or face shield",
                "Put on gloves, pulling cuffs over gown wrists",
              ],
            },
            {
              id: "ncm103-u3-p1-s-sim2",
              kind: "simulation",
              simKind: "sequence",
              title: "Removing PPE in the Correct Order",
              summary: "Doffing order matters — drag to sequence.",
              minutes: 5,
              skills: ["infection-control"],
              instruction: "Arrange the PPE doffing steps in the correct order (top = first).",
              items: [
                "Remove gloves (the most contaminated item)",
                "Remove the gown",
                "Exit the room and perform hand hygiene",
                "Remove goggles or face shield",
                "Remove the mask or respirator last",
                "Perform hand hygiene again",
              ],
            },
            {
              id: "ncm103-u3-p1-s-quiz",
              kind: "quiz",
              title: "Quiz: Infection Control",
              summary: "5 questions on standard precautions.",
              minutes: 8,
              passThreshold: 0.7,
              questions: [
                {
                  id: "q1",
                  prompt: "Standard Precautions apply to:",
                  options: [
                    "Only patients with known infections",
                    "All patients",
                    "Only isolation rooms",
                    "Only the ICU",
                  ],
                  correctIndex: 1,
                  explanation:
                    "Standard Precautions apply to ALL patients — we can't always identify who is infectious.",
                },
                {
                  id: "q2",
                  prompt:
                    "For a patient with suspected C. difficile, hand hygiene must use:",
                  options: [
                    "Alcohol-based rub only",
                    "Soap and water",
                    "No hand hygiene needed",
                    "Wet wipes",
                  ],
                  correctIndex: 1,
                  explanation:
                    "Alcohol doesn't kill C. difficile spores — soap and water is required.",
                },
                {
                  id: "q3",
                  prompt: "Which is NOT one of WHO's Five Moments?",
                  options: [
                    "Before touching a patient",
                    "Before a clean/aseptic procedure",
                    "Before eating lunch",
                    "After touching patient surroundings",
                  ],
                  correctIndex: 2,
                  explanation:
                    "'Before eating' is a good habit but not one of the five clinical Moments.",
                },
                {
                  id: "q4",
                  prompt: "When putting PPE on, gloves go on:",
                  options: [
                    "First, before the gown",
                    "Last, over the gown cuffs",
                    "At the same time as the mask",
                    "It doesn't matter",
                  ],
                  correctIndex: 1,
                  explanation: "Gloves are donned last, pulled over the gown cuffs to seal the wrist.",
                },
                {
                  id: "q5",
                  prompt: "Contact precautions are added for:",
                  options: [
                    "All patients",
                    "Pathogens spread by direct/indirect contact (e.g. MRSA)",
                    "Airborne diseases only",
                    "No specific reason",
                  ],
                  correctIndex: 1,
                  explanation: "Contact precautions target organisms spread by touch.",
                },
              ],
            },
          ],
        },
      ],
    },

    {
      id: "ncm103-u4",
      title: "Medication Administration",
      summary: "The 10 Rights, dosage calculation, and safe routes.",
      icon: "💊",
      hours: 14,
      pathways: [
        {
          id: "ncm103-u4-p1",
          title: "The 10 Rights of Medication Administration",
          summary: "Your safety checklist for every drug, every time.",
          icon: "💉",
          steps: [
            {
              id: "ncm103-u4-p1-s-video",
              kind: "video",
              title: "Medication Safety Essentials",
              summary: "Why the rights exist and how errors happen.",
              minutes: 7,
              transcript:
                "Medication errors are among the most common preventable harms in healthcare. The 'rights' are a structured cross-check the nurse performs to make sure each dose reaches the right patient, the right way, at the right time.",
            },
            {
              id: "ncm103-u4-p1-s-reading",
              kind: "reading",
              title: "The 10 Rights of Medication Administration",
              summary: "From the classic 5 to the modern 10.",
              minutes: 9,
              source: "StatPearls (NIH): Nursing Rights of Medication Administration",
              skills: ["medication-administration"],
              body: [
                "The original **5 rights** have expanded to **10** to close gaps that caused errors:",
                "",
                "1. **Right Patient** — verify with two identifiers (name + DOB).",
                "2. **Right Medication** — match the drug to the order.",
                "3. **Right Dose** — check and recalculate the dose.",
                "4. **Right Route** — PO, IV, IM, SC, SL, topical, etc.",
                "5. **Right Time** — respect frequency and timing.",
                "6. **Right Documentation** — record immediately after, never before.",
                "7. **Right Reason / Indication** — know WHY this drug is given.",
                "8. **Right Response / Evaluation** — assess the effect.",
                "9. **Right Education / Information** — teach the patient.",
                "10. **Right to Refuse** — respect autonomy; document and notify.",
                "",
                "Verify the rights **at least three times**: when pulling the drug, when preparing, and at the bedside.",
              ].join("\n"),
              takeaways: [
                "10 Rights: patient, medication, dose, route, time, documentation, reason, response, education, refusal.",
                "Use two patient identifiers, not the room number.",
                "Document AFTER giving the drug, never before.",
              ],
            },
            {
              id: "ncm103-u4-p1-s-practice",
              kind: "practice",
              title: "Walk the 10 Rights at the Bedside",
              summary: "Check off each right before, during, and after administration.",
              minutes: 12,
              skills: ["medication-administration"],
              checklist: [
                "Verify two patient identifiers",
                "Confirm drug name against the order",
                "Calculate and double-check the dose",
                "Confirm the route is correct",
                "Check the scheduled time",
                "Plan to document immediately after",
                "State the indication (reason)",
                "Plan how you'll evaluate the response",
                "Prepare patient teaching points",
                "Confirm the patient consents (right to refuse)",
              ],
              equipment: ["Medication administration record (MAR)", "Patient ID band", "Calculator"],
            },
            {
              id: "ncm103-u4-p1-s-sim",
              kind: "simulation",
              simKind: "sequence",
              title: "Safe Injection Procedure Sequence",
              summary: "Put the safe-injection steps in order.",
              minutes: 6,
              skills: ["medication-administration"],
              instruction: "Arrange the safe-injection steps in the correct order.",
              items: [
                "Perform hand hygiene and don gloves",
                "Verify the 10 rights and check expiry dates",
                "Draw up the correct dose using a sterile technique",
                "Confirm two patient identifiers at the bedside",
                "Administer via the correct route",
                "Document immediately after administration",
                "Evaluate the patient's response",
              ],
            },
            {
              id: "ncm103-u4-p1-s-quiz",
              kind: "quiz",
              title: "Quiz: Medication Administration",
              summary: "6 questions on the rights and safety.",
              minutes: 10,
              passThreshold: 0.7,
              questions: [
                {
                  id: "q1",
                  prompt: "Which pair is a valid two-identifier check?",
                  options: [
                    "Room number and bed",
                    "Name and date of birth",
                    "Diagnosis and room",
                    "Physician and floor",
                  ],
                  correctIndex: 1,
                  explanation: "Name + DOB are standard identifiers; room/bed numbers change and aren't safe.",
                },
                {
                  id: "q2",
                  prompt: "When should you document medication given?",
                  options: [
                    "Before preparing it",
                    "Immediately after administration",
                    "At the end of the shift from memory",
                    "Only if an error occurs",
                  ],
                  correctIndex: 1,
                  explanation: "Document right after giving the drug — never before (it may not be given) or from memory.",
                },
                {
                  id: "q3",
                  prompt: "Order: 500 mg PO. Stock: 250 mg/tablet. How many tablets?",
                  options: ["0.5 tablet", "1 tablet", "2 tablets", "4 tablets"],
                  correctIndex: 2,
                  explanation: "500 ÷ 250 = 2 tablets.",
                },
                {
                  id: "q4",
                  prompt: "'Right to Refuse' means:",
                  options: [
                    "The patient can decline and the nurse documents and notifies",
                    "The nurse can skip the dose if busy",
                    "Refusal means automatic discharge",
                    "It only applies to IV drugs",
                  ],
                  correctIndex: 0,
                  explanation: "Respect autonomy: document the refusal, inform the team, and follow up.",
                },
                {
                  id: "q5",
                  prompt: "The route 'PO' means:",
                  options: ["Intravenous", "Intramuscular", "By mouth (per os)", "Sublingual"],
                  correctIndex: 2,
                  explanation: "PO = per os, by mouth.",
                },
                {
                  id: "q6",
                  prompt: "How many times should you verify the rights per dose?",
                  options: ["Once", "Twice", "At least three times", "Only for high-alert drugs"],
                  correctIndex: 2,
                  explanation: "Best practice: verify when pulling, when preparing, and at the bedside.",
                },
              ],
            },
          ],
        },
      ],
    },

    {
      id: "ncm103-u5",
      title: "Emergency Care",
      summary: "BLS, choking, hemorrhage control, and recognizing deterioration.",
      icon: "🚑",
      hours: 8,
      pathways: [
        {
          id: "ncm103-u5-p1",
          title: "Basic Life Support & First Response",
          summary: "CPR, choking, and the chain of survival.",
          icon: "❤️‍🩹",
          steps: [
            {
              id: "ncm103-u5-p1-s-video",
              kind: "video",
              title: "Adult CPR & the Chain of Survival",
              summary: "Hands-only CPR and the AED.",
              minutes: 8,
              transcript:
                "The chain of survival: early recognition and call for help, early CPR, rapid defibrillation, and advanced care. For adults, push hard and fast — at least 5 cm depth and 100–120 compressions per minute, full chest recoil.",
            },
            {
              id: "ncm103-u5-p1-s-reading",
              kind: "reading",
              title: "CPR Rates, Ratios, and Choking",
              summary: "The numbers you must memorize.",
              minutes: 7,
              source: "AHA/ILCOR Basic Life Support guidelines",
              skills: ["emergency-care"],
              body: [
                "## Adult CPR",
                "- **Compression rate:** 100–120 per minute",
                "- **Compression depth:** at least 5 cm (2 in), avoiding > 6 cm",
                "- **Ratio:** 30 compressions : 2 breaths (single or two rescuers)",
                "- **Allow full chest recoil** between compressions",
                "",
                "## Choking (responsive adult)",
                "- Encourage cough → if ineffective, **5 back blows** then **5 abdominal thrusts** (Heimlich) → alternate.",
                "- If the victim becomes unresponsive, start CPR and look in the mouth before breaths.",
                "",
                "## Early warning scores",
                "- Track vitals trends; a rising RR and falling BP or SpO₂ often precede collapse. Use your facility's early-warning tool (e.g. MEWS/NEWS).",
              ].join("\n"),
              takeaways: [
                "Push 100–120/min, ≥ 5 cm deep, full recoil.",
                "30:2 compression-to-ventilation ratio.",
                "Choking: 5 back blows + 5 abdominal thrusts, alternating.",
              ],
            },
            {
              id: "ncm103-u5-p1-s-sim",
              kind: "simulation",
              simKind: "decision",
              title: "Patient Scenario: The Collapsed Patient",
              summary: "A patient collapses in the hallway. Act fast.",
              minutes: 7,
              skills: ["emergency-care"],
              entry: "start",
              nodes: {
                start: {
                  id: "start",
                  scenario:
                    "An adult visitor suddenly collapses in the hallway. You tap and shout — no response, no normal breathing. What is your FIRST action?",
                  patient: {
                    name: "Visitor",
                    vitals: { Responsiveness: "Unresponsive", Breathing: "Absent/agonal" },
                    context: "Sudden collapse, witnessed.",
                  },
                  choices: [
                    {
                      id: "c1",
                      label: "Call for help / activate emergency response and get an AED",
                      next: "help",
                      feedback: "Correct — summon help and a defibrillator, then start CPR.",
                    },
                    {
                      id: "c2",
                      label: "Start CPR without telling anyone",
                      next: "alone",
                      feedback: "CPR matters, but you also need help and an AED now.",
                    },
                    {
                      id: "c3",
                      label: "Wait to see if he wakes up",
                      next: "wait",
                      feedback: "Dangerous — every minute without CPR/defibrillation cuts survival.",
                    },
                  ],
                },
                help: {
                  id: "help",
                  scenario:
                    "Help is coming and an AED is on the way. What do you do while you wait?",
                  choices: [
                    {
                      id: "h1",
                      label: "Begin chest compressions 100–120/min, ≥ 5 cm deep",
                      next: "cpr",
                      feedback: "Yes — high-quality compressions are the priority.",
                    },
                    {
                      id: "h2",
                      label: "Leave to find the family",
                      next: "leave",
                      feedback: "Stay with the patient; delegate tasks to bystanders.",
                    },
                  ],
                },
                cpr: {
                  id: "cpr",
                  scenario:
                    "The AED arrives. After applying pads, it advises a shock. What now?",
                  choices: [
                    {
                      id: "cp1",
                      label: "Ensure no one is touching the patient, deliver the shock, resume CPR",
                      next: "win",
                      feedback: "Correct — 'clear' the patient, shock, then immediately resume compressions.",
                    },
                    {
                      id: "cp2",
                      label: "Continue compressions through the shock",
                      next: "shock",
                      feedback: "Never shock through a rescuer — stand clear, shock, resume.",
                    },
                  ],
                },
                win: {
                  id: "win",
                  scenario: "Excellent — you've followed the chain of survival.",
                  success: true,
                  debrief:
                    "Sequence: recognize → call for help/AED → high-quality CPR → defibrillate as advised → resume CPR → hand over to advanced care.",
                },
                alone: {
                  id: "alone",
                  scenario: "Get help first — a lone rescuer can't defibrillate and do CPR indefinitely.",
                  debrief: "Call out for help or use a phone on speaker while starting compressions.",
                  choices: [{ id: "a1", label: "Call for help", next: "start" }],
                },
                wait: {
                  id: "wait",
                  scenario: "Don't wait — sudden collapse with no breathing is cardiac arrest until proven otherwise.",
                  debrief: "Delays cost lives; act within seconds.",
                  choices: [{ id: "w1", label: "Act now", next: "start" }],
                },
                leave: {
                  id: "leave",
                  scenario: "Never leave an arrest victim alone — delegate instead.",
                  debrief: "Use bystanders to call, fetch the AED, and locate family.",
                  choices: [{ id: "l1", label: "Stay and delegate", next: "help" }],
                },
                shock: {
                  id: "shock",
                  scenario: "Always 'clear' the patient before a shock.",
                  debrief: "Touching the patient during a shock endangers the rescuer.",
                  choices: [{ id: "s1", label: "Clear and shock", next: "cpr" }],
                },
              },
            },
            {
              id: "ncm103-u5-p1-s-quiz",
              kind: "quiz",
              title: "Quiz: Emergency Care",
              summary: "4 questions on BLS basics.",
              minutes: 6,
              passThreshold: 0.7,
              questions: [
                {
                  id: "q1",
                  prompt: "Adult chest compression rate is:",
                  options: ["60–80/min", "100–120/min", "150–180/min", "As fast as possible"],
                  correctIndex: 1,
                  explanation: "100–120 compressions per minute.",
                },
                {
                  id: "q2",
                  prompt: "Compression-to-ventilation ratio for an adult is:",
                  options: ["15:2", "30:2", "10:1", "50:5"],
                  correctIndex: 1,
                  explanation: "30 compressions to 2 breaths for adults.",
                },
                {
                  id: "q3",
                  prompt: "For a responsive choking adult with ineffective cough, you give:",
                  options: [
                    "5 back blows + 5 abdominal thrusts, alternating",
                    "Sips of water",
                    "Immediate abdominal x-ray",
                    "Lay them flat and wait",
                  ],
                  correctIndex: 0,
                  explanation: "Alternate 5 back blows and 5 abdominal thrusts.",
                },
                {
                  id: "q4",
                  prompt: "Before an AED shock, you must:",
                  options: [
                    "Keep holding the patient",
                    "Ensure nobody is touching the patient",
                    "Remove only the shirt",
                    "Give two breaths",
                  ],
                  correctIndex: 1,
                  explanation: "'Clear' the patient so no rescuer is shocked.",
                },
              ],
            },
          ],
        },
      ],
    },

    {
      id: "ncm103-u6",
      title: "Documentation & Communication",
      summary: "Clear charting, SBAR handoffs, and therapeutic communication.",
      icon: "📝",
      hours: 6,
      pathways: [
        {
          id: "ncm103-u6-p1",
          title: "Charting & SBAR Handoff",
          summary: "Document once, clearly, and legally.",
          icon: "📋",
          steps: [
            {
              id: "ncm103-u6-p1-s-video",
              kind: "video",
              title: "SBAR: Structured Handoff",
              summary: "Situation, Background, Assessment, Recommendation.",
              minutes: 6,
              transcript:
                "SBAR standardizes communication. Situation: who and what's happening now. Background: relevant history. Assessment: your clinical read. Recommendation: what you need.",
            },
            {
              id: "ncm103-u6-p1-s-reading",
              kind: "reading",
              title: "Principles of Good Documentation",
              summary: "If it isn't documented, it didn't happen.",
              minutes: 7,
              source: "OpenStax, Fundamentals of Nursing",
              skills: ["documentation"],
              body: [
                "- **Timely** — chart as close to care as possible.",
                "- **Accurate & factual** — record what you observed/did, not opinions.",
                "- **Complete & legible** — no blank lines; use correct abbreviations.",
                "- **Signed** — every entry dated, timed, and signed.",
                "- **Never alter** — late entries are addenda, never overwrites.",
                "",
                "**SBAR handoff example:**",
                "",
                "- **S:** 'Mr. Reyes, post-op day 1, new-onset fever 38.6°C.'",
                "- **B:** 'Admitted for appendectomy, no pre-existing infection.'",
                "- **A:** 'Wound looks clean; lungs clear; HR 102.'",
                "- **R:** 'Request order for cultures and antipyretic; will monitor q15.'",
              ].join("\n"),
              takeaways: [
                "Document facts, not opinions; sign every entry.",
                "SBAR = Situation, Background, Assessment, Recommendation.",
                "Never overwrite — add a late entry.",
              ],
            },
            {
              id: "ncm103-u6-p1-s-practice",
              kind: "practice",
              title: "Write an SBAR Handoff",
              summary: "Hand off a patient using SBAR.",
              minutes: 10,
              skills: ["documentation"],
              checklist: [
                "Situation: identify patient + the immediate problem",
                "Background: relevant history and recent events",
                "Assessment: your current clinical findings",
                "Recommendation: what you need from the receiver",
              ],
              equipment: ["SBAR template", "Patient chart"],
            },
            {
              id: "ncm103-u6-p1-s-quiz",
              kind: "quiz",
              title: "Quiz: Documentation",
              summary: "3 questions on charting.",
              minutes: 5,
              passThreshold: 0.7,
              questions: [
                {
                  id: "q1",
                  prompt: "In SBAR, the 'A' stands for:",
                  options: ["Action", "Assessment", "Allergy", "Admission"],
                  correctIndex: 1,
                  explanation: "Assessment — your clinical interpretation of the situation.",
                },
                {
                  id: "q2",
                  prompt: "You realize an entry from 2 hours ago is wrong. You should:",
                  options: [
                    "Overwrite it so the record is tidy",
                    "Write a new late-entry addendum with the correction",
                    "Erase it",
                    "Ignore it",
                  ],
                  correctIndex: 1,
                  explanation: "Never alter a record — add a signed late entry.",
                },
                {
                  id: "q3",
                  prompt: "Good documentation is best described as:",
                  options: [
                    "Opinionated and lengthy",
                    "Timely, factual, complete, and signed",
                    "Written at end of shift from memory",
                    "Optional for routine care",
                  ],
                  correctIndex: 1,
                  explanation: "Document near the time of care, factually and completely.",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
